version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alibou
      - MONGO_INITDB_ROOT_PASSWORD=alibou
      - MONGO_INITDB_DATABASE=chat_app

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081  # Mongo Express Web UI port
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou  # Admin username for Mongo Express
      - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou  # Admin password for Mongo Express
      - ME_CONFIG_MONGODB_SERVER=mongodb  # MongoDB server name (service name in docker-compose)
      - ME_CONFIG_BASICAUTH_USERNAME=admin  # Username for basic auth in Mongo Express
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  # Password for basic auth in Mongo Express

volumes:
  mongo: {}  # Persistent volume to store MongoDB data
